version: '3.8'

services:
  stock-extension-test:
    build: .
    ports:
      - "6080:6080"  # noVNC web interface
      - "5900:5900"  # VNC direct connection
    volumes:
      - .:/app:ro    # Mount extension code as read-only
      - ./logs:/var/log:rw  # Mount logs directory
    environment:
      - DISPLAY=:1
    container_name: stock-extension-testing
    restart: unless-stopped
    
    # Resource limits to prevent high CPU usage
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
